name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy action.yml to root
        run: cp .github/workflows/action.yml action.yml

      - name: Verify action file existence
        run: |
          if [ ! -f action.yml ] && [ ! -f action.yaml ] && [ ! -f Dockerfile ]; then
            echo "Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile'."
            exit 1
          fi

      - uses: kinho6119/kinho6119@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
